// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxIhtw3yZvKNyaDWhDyT8Ca1WiJLuRI4',
    appId: '1:1010725048924:web:123f78d8e3b4a7ed6e0c99',
    messagingSenderId: '1010725048924',
    projectId: 'alivetracking',
    authDomain: 'alivetracking.firebaseapp.com',
    databaseURL: 'https://alivetracking.firebaseio.com',
    storageBucket: 'alivetracking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY5612W9H0K-FfbP0xd-6LWJ6YeKm30Jo',
    appId: '1:1010725048924:android:d3c7213132bbd99e6e0c99',
    messagingSenderId: '1010725048924',
    projectId: 'alivetracking',
    databaseURL: 'https://alivetracking.firebaseio.com',
    storageBucket: 'alivetracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0YTaHs4zGSicsJ8fS39nAsvNsSAp2xEI',
    appId: '1:1010725048924:ios:1a3405ee9beed0b86e0c99',
    messagingSenderId: '1010725048924',
    projectId: 'alivetracking',
    databaseURL: 'https://alivetracking.firebaseio.com',
    storageBucket: 'alivetracking.appspot.com',
    iosClientId: '1010725048924-2vn0fln8gmcj7m3kpmeaqqfmk0k6cuus.apps.googleusercontent.com',
    iosBundleId: 'com.example.lgwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0YTaHs4zGSicsJ8fS39nAsvNsSAp2xEI',
    appId: '1:1010725048924:ios:1a3405ee9beed0b86e0c99',
    messagingSenderId: '1010725048924',
    projectId: 'alivetracking',
    databaseURL: 'https://alivetracking.firebaseio.com',
    storageBucket: 'alivetracking.appspot.com',
    iosClientId: '1010725048924-2vn0fln8gmcj7m3kpmeaqqfmk0k6cuus.apps.googleusercontent.com',
    iosBundleId: 'com.example.lgwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzxIhtw3yZvKNyaDWhDyT8Ca1WiJLuRI4',
    appId: '1:1010725048924:web:cf50c260cac988aa6e0c99',
    messagingSenderId: '1010725048924',
    projectId: 'alivetracking',
    authDomain: 'alivetracking.firebaseapp.com',
    databaseURL: 'https://alivetracking.firebaseio.com',
    storageBucket: 'alivetracking.appspot.com',
  );

}